### ISSUE TITLE
There are three serious mistakes.

### ISSUE THREAD

**Issue by joseliko7** [1hakr/AnExplorer#28]
When importing these errors appear:

C:\Users\Jose\Desktop\AnExplorer-master\app\build\intermediates\res\merged\otherPro\release\values-v23\values-v23.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(18) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:Execution failed for task ':app:processOtherProReleaseResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Jose\AppData\Local\Android\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by rachitmishra** [comment]
We are looking into this
