### ISSUE TITLE
StorageVolume does not contain info about external storages in API 23.

### ISSUE THREAD

**Issue by isabsent** [1hakr/AnExplorer#31]
[As you can see](https://www.dropbox.com/sh/cqai6x50u46q50i/AAA7Ti4Wk5t8l_nkuELPikgTa?dl=0) it is impossible to read/write to USB OTG flash drive on Nexus 5 (Marshmallow 6.0.1). The reason in class **android.os.storage.StorageVolume**. It does not contain info which you need starting from API 23. Nevertheless, ES Explorer can do that somehow.

**Comment by 1hakr** [comment]
Now USB OTG is supported on nexus devices in in API 23 and above with the latest version
