### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [1hakr/AnExplorer#43]
Would you consider publishing the `.apk` file on Github – for those not using Google Play?

**Comment by 1hakr** [comment]
Sure @IzzySoft, i didnt realise there are people using github for my AnExplorer. I will start publishing it on Github from now on. Here you go https://github.com/1hakr/AnExplorer/releases/tag/3.4

**Comment by IzzySoft** [comment]
Thanks a lot!

Yeah, there are some people who cannot access Playstore (device came w/o GApps, or they're sitting in a "restricted zone") – and those who do not want to, or as little as possible, be dependent on GServices (like me: I rid my device of that, using microG instead). All of them can use the F-Droid app – but not all apps are available there.

To increase the number of apps available that way, I created [my own repo](https://android.izzysoft.de/repo), which now also includes your great file explorer, [see here](https://apt.izzysoft.de/fdroid/index/apk/dev.dworks.apps.anexplorer). Feel free to link to this address as "alternative source": it will usually be updated within 24 hours of your creating a new release at Github and adding an `.apk` to it, and folks can use it with the F-Droid app (adding my repo) so they will be notified on updates :smiley_cat:
