### ISSUE TITLE
Missing Keystore.properties

### ISSUE THREAD

**Issue by Technologx** [1hakr/AnExplorer#45]
I'm running into this issue http://stackoverflow.com/questions/41646965/neither-path-nor-basedir-may-be-null-or-empty-string

**Comment by 1hakr** [comment]
create a local file keystore.properties and add these into that
```
keyStore=<path to xxxx.keystore>
keyStorePassword=<keystore password>
keyAlias=<key alias>
keyAliasPassword=<key alias password>
```

**Comment by Technologx** [comment]
What version of JDE or Android Studio do I need?
