### ISSUE TITLE
License Key & Amazon API key

### ISSUE THREAD

**Issue by Technologx** [1hakr/AnExplorer#54]
Where are these placed?

**Comment by 1hakr** [comment]
License key? are you talking about keystore? You should create your own keystore. And there is no amazon api key

**Comment by Technologx** [comment]
I get this when trying to create the amazon flavor:

```
Error:Execution failed for task ':app:processAmazonFreeReleaseGoogleServices'.
> Missing api_key/current_key object
```

**Comment by 1hakr** [comment]
create your own keystore and a properties file like this https://github.com/1hakr/AnExplorer/issues/45 and it should work

**Comment by Technologx** [comment]
I already have the keystore.properties file made.
