### ISSUE TITLE
please, add a shortcut file folder to the Home screen on android programmatically [duplicate] TANKS good 1hkr

### ISSUE THREAD

**Issue by wansm** [1hakr/AnExplorer#57]
please, add a shortcut file folder to the Home screen on android programmatically [duplicate] TANKS good 1hkr

**Comment by 1hakr** [comment]
I don't understand. Can you explain?

**Comment by 1hakr** [comment]
Will reopen once there is more info.

**Comment by aveilleux** [comment]
I believe @wansm is asking for the ability to create shortcuts on the Home screen to files and folders, which is a pretty useful feature of other FMs. I have attached an example of this functionality to this post.

![screenshot_2018-11-12-11-17-37](https://user-images.githubusercontent.com/307077/48362902-adb85880-e672-11e8-8c61-5a5e334ebcf8.jpg)

![screenshot_2018-11-12-11-18-03](https://user-images.githubusercontent.com/307077/48362868-9ed1a600-e672-11e8-84d2-6f3aff51d16c.jpg)
