### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by duwurensheng010** [1hakr/AnExplorer#58]
Error:Unable to find method 'org.gradle.api.artifacts.dsl.DependencyHandler.registerTransform(Ljava/lang/Class;Lorg/gradle/api/Action;)V'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

**Comment by 1hakr** [comment]
could be gradle issue as you have pointed. Closing the issue.
