### ISSUE TITLE
Why the delay? 

### ISSUE THREAD

**Issue by enwokoma** [1hakr/AnExplorer#69]
I have noticed that this project isn't updated regularly, don't you think some new features should be added, anexplorer is too good to be abandoned like this. My suggestion is to add an inbuilt IMAGE VIEWER, AUDIO and VIDEO PLAYER and one more important feature that's missing is ENCRYPTION, I guess with that, we should really standout different from the rest of other file managers, I also think we need Anexplorer to popup as an option when a user clicks on a ZIP or RAR file from a different application on his/her (I think making an intent or something for this should do the work just fine). What do you think? @1hakr

**Comment by 1hakr** [comment]
Hey @enwokoma just been busy. But the best part of why we opensource projects is the community and people like you can contribute aswell. I would love to build new things but i would love more to see community take it forward.

**Comment by enwokoma** [comment]
Sure! However I can help, I would try my best to make that possible! Do
have a nice day.
Now u can close the issue, just used it to get your attention 😉

**Comment by 1hakr** [comment]
Sure mate!
