### ISSUE TITLE
[Bug] Display error

### ISSUE THREAD

**Issue by Cmd-Cmd** [1hakr/AnExplorer#78]
1. Click into "Internal Storage"
2. Click icon of some item for entering multi choice mode
3. Click floating actions menu to create a folder (Then it will auto open into the new directory)
4. Back, and you can see this little bug of action mode title

**Comment by gigabytedevelopersinc** [comment]
Sorry, but am not able to reproduce this. Could you elaborate more on the
bug which you speak of, or send your logcat!

**Comment by vaibhavsharma316** [comment]
Can you please send a screenshot what is that bug actually. I have implemented your steps . When i click on the back button after creating the directory in toolbar title it is showing 1 (as i have selected only one file) is this the bug that you are talking about?

**Comment by Cmd-Cmd** [comment]
Sorry for waiting so long time...
![Before Create](https://github.com/Cmd-Cmd/Draw.io/blob/master/Screenshot_20171215-172051.png)
![After Create](https://github.com/CmAd-Cmd/Draw.io/blob/master/Screenshot_20171215-172113.png)

**Comment by vaibhavsharma316** [comment]
ok i understood . Thanks for sharing

**Comment by 1hakr** [comment]
this issue no longer exists
