### ISSUE TITLE
[Request] Add to F-Droid store

### ISSUE THREAD

**Issue by JuniorJPDJ** [1hakr/AnExplorer#82]
You can add your app to F-Droid repository, it would let some people not wanting google on their phones use it ;)

Eg. Today I was looking for great file manager in F-Droid, and only one good enough was Amaze.
Your's better.

**Comment by DJCrashdummy** [comment]
fyi: there is a _Requests For Packaging_ (https://gitlab.com/fdroid/rfp/issues/536).

**Comment by JuniorJPDJ** [comment]
@1hakr https://gitlab.com/fdroid/rfp/issues/536#note_75238292
There is question for you if they can build Pro version and share it in repository

**Comment by JuniorJPDJ** [comment]
Can be resolved, request merged to f-droid repo, waiting for first build

**Comment by licaon-kter** [comment]
@1hakr Any idea?
https://gitlab.com/fdroid/fdroiddata/issues/1328#note_134215637
