### ISSUE TITLE
bug found in AnExplorer while trial to compress

### ISSUE THREAD

**Issue by darewealth** [1hakr/AnExplorer#83]
#### Expected behavior
I compress file in AnExplorer application which I expect the file should be able to compress successfully 

#### Actual behavior
After open the application. I trial to compress one file but it was just rolling without compress any file

#### How to reproduce
(1)	Download [AnExplorer](https://play.google.com/store/apps/details?id=dev.dworks.apps.anexplorer) application 

(2)	 launch It and open 

(3)	Go to any file you want to compress

 Device used: Gionee P5 mini

Operating system: Android version 5.1

*App version 3.7

#### Recording Of The Bug
  https://youtu.be/-sMw_pg1M4g
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@darewealth/bug-found-in-anexplorer-while-trial-to-compress">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by 1hakr** [comment]
Check the latest version. This issue should have been fixed.
