### ISSUE TITLE
Audio category opens music files in their albums and it can be sharing but no app supports the type of document.

### ISSUE THREAD

**Issue by kodeblacc** [1hakr/AnExplorer#92]
The audio category view music files in their albums which can be shared but seems not to be compatible with any software.
Sharing the file to [phone saver](https://play.google.com/store/apps/details?id=link.standen.michael.phonesaver) and [Amaze File Manager](https://play.google.com/store/apps/details?id=com.amaze.filemanager) caused those apps to crash.

**Comment by gigabytedevelopersinc** [comment]
> Sharing the file to phone saver and Amaze File Manager caused those apps to crash.

This clearly shows that it isn't a fault from AnExplorer! But rather, it's an issue with the afore mentioned applications!

**Comment by kodeblacc** [comment]
Oh okay. Thanks for clarifying. I thought so too.

**Comment by gigabytedevelopersinc** [comment]
You are welcome! 

**Team Gigabyte Developers**
