### ISSUE TITLE
Storage and RAM usage bars don't always show up

### ISSUE THREAD

**Issue by contrapunctus-1** [1hakr/AnExplorer#95]
Hi, thanks for writing this beautiful file manager and for adding it to F-Droid.

I'm using v3.8 from F-Droid on a Nokia 6.1, Android 8.1. I've noticed a bug - sometimes, the storage and RAM usage bars don't show up. Launching the app again usually fixes it.

**Comment by 1hakr** [comment]
This is fixed in the upcoming version 4.0.0
