### ISSUE TITLE
Why does the app connect to Amazon/Youtube?

### ISSUE THREAD

**Issue by licaon-kter** [1hakr/AnExplorer#97]
F-Droid [build](https://f-droid.org/en/packages/dev.dworks.apps.anexplorer.pro/) `gradle=other,pro` 3.8

Steps:
1. Start the app

Results:
![anexpro](https://user-images.githubusercontent.com/2282799/44841461-eda29e80-ac32-11e8-9bf3-a07963b78309.jpg)

And the Github APK (installed via @IzzySoft F-Droid repo) connects to `accounts.youtube.com:443` instead

**Comment by IzzySoft** [comment]
That asks for `NonFreeNet` if not fixed (in my repo, I already have tagged it `Ads,NonFreeDep,Tracking` for Crashlytics, DoubleClick, Firebase Analytics, GMS). For what are those requests to YT/Amazon needed? And I hope the `80` doesn't mean the port (unencrypted http)?

**Comment by licaon-kter** [comment]
Yup that's port 80...

**Comment by IzzySoft** [comment]
Double-Ouch then …

**Comment by ADepic** [comment]
Why has the official issue tracker not got these anti features. If it really connects to youtube & uses firebase analytics it should straight up be removed

**Comment by licaon-kter** [comment]
It can connect to anything. It can't use Firebase/Analytics, else it can't be bui

**Comment by licaon-kter** [comment]
@1hakr Any input?

**Comment by licaon-kter** [comment]
Ok, now please read my issue again, and respond to my question. Thanks

**Comment by 1hakr** [comment]
@licaon-kter My bad 

You were not asked to connect to youtube/amazon. Or Why does the app connect not Youtube/Amazon? 

Is this your question? 
If yes then ideally the app shouldn't connect to anything in pro version. Need to look into this further.
If no, please can you put your question again.

Also, can you try the `gradle=play,pro` version?

BTW what app is the screenshot from? Currently, the apk uploaded here is the Free version and not the pro version.

**Comment by licaon-kter** [comment]
@1hakr 
> Is this your question?

`Why does the app connect to Amazon/Youtube?`

> Also, can you try the gradle=play,pro version?

Why? What's different?

> BTW what app is the screenshot from? 

https://github.com/M66B/NetGuard

**Comment by licaon-kter** [comment]
3.9 on F-Droid, still trying to connect :(

**Comment by Poussinou** [comment]
@licaon-kter I don't like the fact to have such a problematic app in our F-Droid official repo. Could you try [this app](https://f-droid.org/packages/org.secuso.privacyfriendlynetmonitor/) with AnExplorer to see what it says ?

**Comment by 1hakr** [comment]
@licaon-kter 
>Why? Don't I need an actual Google key to build it anyway?
No, you can use your own key or debug key to build it

I have checked and it looks like the library https://github.com/javiersantos/AppUpdater to check for updates on the latest version which connects to Google or Amazon.

I hope this answers your question.

**Comment by licaon-kter** [comment]
@1hakr Ok, now disable that check when the app is **not** installed from Amazon, as expected,

**Comment by licaon-kter** [comment]
Trying to compile this, but you've brought in another non-free
`implementation "com.google.android.gms:play-services-cast-framework:16.1.0"`

**Comment by TacoTheDank** [comment]
oof ouch
